apiVersion: apps/v1
kind: Deployment
metadata:
  name: techinsight-api
  namespace: techinsight
spec:
  replicas: 2
  selector:
    matchLabels:
      app: techinsight-api
  template:
    metadata:
      labels:
        app: techinsight-api
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: techinsight-api
        image: lifegoeson34/techinsight-api:v1.0.f95188e
        imagePullPolicy: Always 
        ports: 
          - containerPort: 8080
